name: Merge master to next

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v4

      - name: Merge main into next
        id: merge
        run: |
          git checkout -b next origin/next
          git merge main
          git push origin next

      - name: Create a new PR if there are conflicts
        if: ${{ failure()}}
        run: |
          git checkout -b merge-main-to-next
          git push origin merge-main-to-next
          gh pr create --base next --head merge-main-to-next --title "Merge main into next" --body "This PR was created automatically because there were conflicts when merging main into next."
