name: Merge master to next

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v4
        with:
          ref: next
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch other branches
        run: git fetch origin main

      - uses: fregante/setup-git-user@v2

      - name: Merge main into next
        id: merge
        run: |
          git merge origin/main || { echo "Merge conflict detected, will create a pull request."; git merge --abort; echo "RESULT=failure" >> "$GITHUB_OUTPUT"; exit 1; }
          echo "RESULT=success" >> "$GITHUB_OUTPUT"

      - name: Push changes
        run: git push origin next
        if: steps.merge.outputs.RESULT == 'success'

      - name: Create a new PR if there are conflicts
        uses: peter-evans/create-pull-request@v7
        if: steps.merge.outputs.RESULT == 'failure'
        with:
          title: 'Merge main into next'
          body: 'This PR is created automatically due to merge conflicts.'
          branch: 'merge-main-into-next-${{ github.run_id }}'
