name: Merge master to next

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v4
        with:
          ref: next
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: fregante/setup-git-user@v2

      - name: Reset branch
        run: |
          git fetch origin main:main
          git reset --hard main

      - name: Merge main into next
        id: merge
        run: |
          echo "MERGE_CONFLICT=0" >> "$GITHUB_OUTPUT"
          git merge origin/main || echo "MERGE_CONFLICT=1" >> "$GITHUB_OUTPUT"

      - name: Push changes
        if: steps.merge.outputs.MERGE_CONFLICT == '0'
        run: git push origin next

      - name: Create a new PR if there are conflicts
        if: steps.merge.outputs.MERGE_CONFLICT == '1'
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'Merge main into next'
          body: 'This PR is created automatically due to merge conflicts.'
          branch: 'next-temp'
