name: Merge master to next

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v4

      - name: Merge main into next
        run: |
          git fetch origin next
          git checkout -b next refs/remotes/origin/next
          git merge main --no-ff
          git push origin next

      - name: Create a new PR if there are conflicts
        if: ${{ failure()}}
        run: |
          git checkout -b merge-main-to-next-${{ github.run_number }}
          git push origin merge-main-to-next-${{ github.run_number }}
          gh pr create --base next --head merge-main-to-next --title "Merge main into next" --body "This PR was created automatically because there were conflicts when merging main into next."
