name: Merge master to next

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - name: Merge main into next
        run: |
          git checkout -b next origin/next
          git merge main --no-ff
          git push origin next

      - name: Create a new PR if there are conflicts
        if: ${{ failure()}}
        run: |
          git merge --abort
          git checkout -b merge-main-to-next origin/main
          git push origin merge-main-to-next --force
          gh pr create --base next --head merge-main-to-next --title "Merge main into next" --body "This PR was created automatically because there were conflicts when merging main into next."
