name: Merge master to next

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v4
        with:
          ref: next
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch other branches
        run: git fetch origin main

      - uses: fregante/setup-git-user@v2

      - name: Merge main into next
        id: merge
        run: |
          git merge origin/main
          if [ $? -ne 0 ]
          then
            echo "Merge conflict detected, creating a pull request."
            # Fallback to abort, remove this if you decide to handle conflicts in a different way
            git merge --abort
            echo "RESULT=failure" >> "$GITHUB_OUTPUT"
          else
            echo "RESULT=success" >> "$GITHUB_OUTPUT"
          fi

      - name: Push changes
        run: git push origin next
        if: steps.merge.outputs.RESULT == 'success'

      - name: Create a new PR if there are conflicts
        uses: peter-evans/create-pull-request@v7
        if: steps.merge.outputs.RESULT == 'failure'
        with:
          title: 'Merge main into next'
          body: 'This PR is created automatically due to merge conflicts.'
          branch: 'merge-main-into-next-${{ github.run_id }}'
