name: VRT

on:
  pull_request:
    types: [synchronize, labeled]
    labels:
      - vrt

jobs:
  # ベースブランチのスナップショットを撮る
  expected_snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Install playwright
        run: npx playwright install

      - name: Build storybook
        run: npm run build-storybook
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run vrt:snapshot"

      - name: Upload snapshot
        uses: actions/upload-artifact@v4
        with:
          name: vrt-expected
          path: snapshots

  # PRのスナップショットを撮る
  acutual_snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Install playwright
        run: npx playwright install

      - name: Build storybook
        run: npm run build-storybook
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run vrt:snapshot"

      - name: Upload snapshot
        uses: actions/upload-artifact@v4
        with:
          name: vrt-actual
          path: snapshots

  # スナップショットを比較する
  compare:
    runs-on: ubuntu-latest
    needs: [expected_snapshot, acutual_snapshot]
    steps:
      - name: Checkout head branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install

      - name: Download snapshot
        uses: actions/download-artifact@v4
        with:
          name: vrt-expected
          path: snapshots/expected
      - name: Download snapshot
        uses: actions/download-artifact@v4
        with:
          name: vrt-actual
          path: snapshots/actual

      - name: Compare snapshots
        run: npm run vrt:diff

      - name: Upload report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vrt-report
          path: |
            snapshots/report.html
            snapshots/diff
