name: VRT

on:
  pull_request:
    types: [synchronize, labeled]
    labels:
      - vrt

jobs:
  # ベースブランチのスナップショットを撮る
  expected_snapshot:
    container: mcr.microsoft.com/playwright:v1.50.1-jammy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: 'npm'
      - name: Install dependencies
        run: npm install

      - name: Build storybook
        run: npm run build-storybook
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run vrt:snapshot"

      - name: Upload snapshot
        uses: actions/upload-artifact@v4
        with:
          name: vrt-expected
          path: snapshots

  # Playwrightを使って比較する
  compare:
    container: mcr.microsoft.com/playwright:v1.50.1-jammy
    runs-on: ubuntu-latest
    needs: expected_snapshot
    steps:
      - name: Checkout head branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: 'npm'
      - name: Install dependencies
        run: npm install

      - name: Download snapshot
        uses: actions/download-artifact@v4
        with:
          name: vrt-expected
          path: snapshots

      - name: Build storybook
        run: npm run build-storybook
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run vrt:diff"

      - name: Upload report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vrt-report
          path: playwright-report
