name: VRT

on:
  pull_request:
    types: [synchronize, labeled]

jobs:
  # ベースブランチのスナップショットを撮る
  expected_snapshot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: contains(github.event.label.name, 'vrt')
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Restore cache
        id: restore
        uses: actions/cache/restore@v3
        with:
          key: reg-suit-cache-${{ github.event.pull_request.base.sha }}
          path: snapshots

      - if: steps.restore.outputs.cache-hit != 'true'
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - if: steps.restore.outputs.cache-hit != 'true'
        name: Install dependencies
        run: npm install
      - if: steps.restore.outputs.cache-hit != 'true'
        name: Install Playwright
        run: npx playwright install --with-deps

      - if: steps.restore.outputs.cache-hit != 'true'
        name: Build storybook
        run: npm run build-storybook
      - if: steps.restore.outputs.cache-hit != 'true'
        name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run vrt:snapshot"

      - if: steps.restore.outputs.cache-hit != 'true'
        name: Cache snapshots
        uses: actions/cache/save@v3
        with:
          path: snapshots
          key: reg-suit-cache-${{ github.event.pull_request.base.sha }}

  # Playwrightを使って比較する
  compare:
    container: mcr.microsoft.com/playwright:v1.50.1-jammy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: expected_snapshot
    steps:
      - name: Checkout head branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm install

      - name: Restore snapshots
        uses: actions/cache/restore@v3
        with:
          key: reg-suit-cache-${{ github.event.pull_request.base.sha }}
          path: snapshots

      - name: Build storybook
        run: npm run build-storybook
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run vrt:diff"

      - name: Upload report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vrt-report
          path: playwright-report
